alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: 1fpga.com
    type: PRIMARY
    zone: 1fpga.com
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: onefpga-com
      match:
        path:
          prefix: /
name: onefpga-com
region: nyc
static_sites:
  - environment_slug: hugo
    github:
      branch: main
      deploy_on_push: true
      repo: 1fpga/1fpga.com
    name: onefpga-com
    source_dir: /
    output_dir: /public
    build_command: npm install && hugo build
